#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Svetosila PDS Converter
Converts PDS Markdown files to HTML with unified styling
"""

import os
import re
import sys
from pathlib import Path

# Try to import markdown library
try:
    import markdown
    MARKDOWN_AVAILABLE = True
except ImportError:
    MARKDOWN_AVAILABLE = False
    print("Warning: markdown library not found. Install with: pip install markdown")

# HTML Template
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Светосила</title>
    <link rel="icon" type="image/png" href="{root_path}assets/img/favicon.ico">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{root_path}assets/css/style.css">
    <script>
        window.mermaid = {{
            startOnLoad: true,
            theme: "default",
            securityLevel: "loose"
        }};
    </script>
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
        mermaid.initialize({{ startOnLoad: true }});
    </script>
</head>
<body>
    <!-- Logo Bar -->
    <div class="header" style="background: #2b2b2b; padding: 20px 0; margin-bottom: 0;">
        <div class="header-container" style="max-width: 1400px; margin: 0 auto; padding: 0 20px; display: flex; justify-content: space-between; align-items: center;">
            <a href="{root_path}index.html" style="margin-left: 10px;">
                <img src="{root_path}assets/img/SvetosilaLogoFull.PNG" alt="Светосила" style="height: 50px; display: block;">
            </a>
            <a href="{github_url}" target="_blank" style="color: white; text-decoration: none; font-weight: 500; font-size: 1.1em; transition: opacity 0.2s ease; margin-right: 10px;">GitHub →</a>
        </div>
    </div>

    <!-- Page Title -->
    <div class="page-title-container" style="max-width: 1400px; margin: 0 auto; padding: 40px 20px 20px 20px;">
        {page_title}
    </div>

    <!-- Main Container -->
    <div class="container" style="max-width: 1400px; margin: 0 auto; padding: 0 20px 60px 20px;">
        <!-- Sidebar -->
        <aside class="sidebar">
            <h3>Содержание</h3>
            <ul>
                <!-- TOC will be auto-generated by JS -->
            </ul>
        </aside>

        <!-- Content -->
        <main class="content">
            {content}
        </main>
    </div>

    <script src="{root_path}assets/js/main.js"></script>
</body>
</html>
"""


def add_heading_ids(html_content: str) -> str:
    """Add id attributes to h2 and h3 headings for anchor links"""
    def generate_id(text):
        """Generate a URL-friendly id from heading text"""
        # Remove HTML tags
        text = re.sub(r'<[^>]+>', '', text)
        # Convert to lowercase
        text = text.lower()
        # Replace spaces and special chars with hyphens
        text = re.sub(r'[^\w\s-]', '', text)
        text = re.sub(r'[\s_]+', '-', text)
        # Remove leading/trailing hyphens
        text = text.strip('-')
        return text
    
    def add_id_to_heading(match):
        tag = match.group(1)  # h2 or h3
        content = match.group(2)
        heading_id = generate_id(content)
        return f'<{tag} id="{heading_id}">{content}</{tag}>'
    
    # Add id to h2 and h3 headings
    html_content = re.sub(r'<(h[23])>(.+?)</\1>', add_id_to_heading, html_content)
    
    return html_content


def convert_pds_file(md_file: Path, repo_root: Path, index_root: Path):
    """Convert a single PDS markdown file to HTML"""
    print(f"Converting: {md_file}")
    
    # Read markdown
    with open(md_file, 'r', encoding='utf-8') as f:
        md_content = f.read()
    
    # Special handling for database files - inject schema from corresponding scheme file
    scheme_mapping = {
        'SvetosilaPDS_DB.md': 'SvetosilaPDS_DB_scheme.md',
        'SvetosilaPDS_DB_AC.md': 'SvetosilaPDS_DB_AC_scheme.md',
    }
    if md_file.name in scheme_mapping:
        scheme_file = md_file.parent / scheme_mapping[md_file.name]
        if scheme_file.exists():
            with open(scheme_file, 'r', encoding='utf-8') as f:
                scheme_content = f.read()
            # Extract only the mermaid block from scheme file
            mermaid_match = re.search(r'(```mermaid.*?```)', scheme_content, re.DOTALL)
            if mermaid_match:
                mermaid_block = mermaid_match.group(1)
                # Insert mermaid block after metadata (after "Последнее изменение:" line)
                md_content = re.sub(
                    r'(\*\*Последнее изменение:\*\*[^\n]*\n)',
                    r'\1\n' + mermaid_block + '\n',
                    md_content,
                    count=1
                )
    
    # Get title from first heading
    title_match = re.search(r'^#\s+(.+)$', md_content, re.MULTILINE)
    title = title_match.group(1) if title_match else md_file.stem
    
    # Determine output path
    rel_path = md_file.relative_to(repo_root)
    output_file = index_root / rel_path.with_suffix('.html')
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    # Convert markdown to HTML
    if MARKDOWN_AVAILABLE:
        md = markdown.Markdown(extensions=[
            'extra',  # Includes: tables, fenced_code, attr_list, def_list, footnotes, abbr
            'sane_lists',  # Better list handling
        ])
        html_content = md.convert(md_content)
        
        # Add id attributes to headings for anchor links
        html_content = add_heading_ids(html_content)
        
        # Post-process: Convert Mermaid code blocks to div.mermaid
        def replace_mermaid(match):
            code = match.group(1)
            # Unescape HTML entities for Mermaid
            code = code.replace('&quot;', '"')
            code = code.replace('&amp;', '&')
            code = code.replace('&lt;', '<')
            code = code.replace('&gt;', '>')
            return f'<div class="mermaid">{code}</div>'
        
        html_content = re.sub(
            r'<pre><code class="language-mermaid">(.*?)</code></pre>',
            replace_mermaid,
            html_content,
            flags=re.DOTALL
        )
    else:
        # Fallback: simple conversion
        html_content = md_content
        html_content = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html_content, flags=re.MULTILINE)
        html_content = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html_content, flags=re.MULTILINE)
        html_content = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html_content, flags=re.MULTILINE)
        html_content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_content)
    
    # Determine relative paths
    rel_from_index = output_file.relative_to(index_root)
    depth = len(rel_from_index.parts) - 1
    root_path = '../' * depth if depth > 0 else ''
    
    # GitHub URL
    github_url = f"https://github.com/KhudyakovAlex/Svetosila/blob/main/{rel_path}"
    
    # Extract h1 from content for page title
    h1_match = re.search(r'<h1>(.*?)</h1>', html_content, re.DOTALL)
    if h1_match:
        page_title = f'<h1 style="color: #2b2b2b; font-size: 2.25em; margin: 0; padding-bottom: 15px; border-bottom: 3px solid #ff860e; font-weight: normal;">{h1_match.group(1)}</h1>'
        # Remove h1 from content
        html_content = re.sub(r'<h1>.*?</h1>', '', html_content, count=1, flags=re.DOTALL)
    else:
        page_title = ''
    
    # Fill template
    html = HTML_TEMPLATE.format(
        title=title,
        root_path=root_path,
        github_url=github_url,
        page_title=page_title,
        content=html_content
    )
    
    # Write HTML
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f"  > Created: {output_file}")


def convert_all_pds():
    """Convert all PDS markdown files"""
    print("="*60)
    print("Svetosila PDS Converter")
    print("="*60)
    
    # Get repository root (parent of PROJECT/INDEX)
    script_dir = Path(__file__).parent
    index_root = script_dir
    repo_root = index_root.parent.parent
    
    # Find all .md files in PDS folder
    pds_folder = repo_root / 'PDS'
    if not pds_folder.exists():
        print(f"Error: PDS folder not found: {pds_folder}")
        return 1
    
    md_files = list(pds_folder.glob('*.md'))
    print(f"\nFound {len(md_files)} markdown files in PDS/\n")
    
    # Convert each file
    for md_file in md_files:
        try:
            convert_pds_file(md_file, repo_root, index_root)
        except Exception as e:
            print(f"  X Error converting {md_file}: {e}")
            import traceback
            traceback.print_exc()
    
    print("\n" + "="*60)
    print("Conversion complete!")
    print("="*60)
    return 0


if __name__ == '__main__':
    sys.exit(convert_all_pds())
